name: CI
on:
  - push

jobs:
  linux-build:
    env:
      DEBIAN_FRONTEND: noninteractive

    runs-on: ubuntu-latest
    container: debian:unstable-slim
    steps:
      - name: Update package repositories
        run: apt update -y

      - name: Upgrade system
        run: apt full-upgrade -y

      - name: Install dependencies
        run: |
          apt install -y \
            --no-install-recommends \
            --no-install-suggests \
            ca-certificates \
            git \
            build-essential \
            nasm \
            cmake \
            pkg-config \
            libx11-dev \
            libxrandr-dev \
            libxinerama-dev \
            libxcursor-dev \
            libxi-dev \
            libvdpau-dev \
            libva-dev \
            liblzma-dev \
            libgtk-3-dev \
            libssl-dev

      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Configure build
        run: |
          mkdir -p build
          cd build
          cmake .. -G"Unix Makefiles"

      - name: Run build
        run: |
          cd build
          cmake --build . --parallel --target MathAnimations
